import React from 'react';

const AIPanel = ({ analysis }) => {
  if (!analysis) return null;

  const severityConfig = {
    High: {
      bar: 'bg-red-500',
      badge: 'bg-red-500/20 text-red-400 border-red-500/30',
      glow: 'shadow-red-500/10',
    },
    Medium: {
      bar: 'bg-amber-500',
      badge: 'bg-amber-500/20 text-amber-400 border-amber-500/30',
      glow: 'shadow-amber-500/10',
    },
    Low: {
      bar: 'bg-emerald-500',
      badge: 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30',
      glow: 'shadow-emerald-500/10',
    }
  };

  const config = severityConfig[analysis.severity] || severityConfig.Medium;

  return (
    <div className={`bg-slate-800 rounded-xl border border-slate-700 overflow-hidden ${config.glow} shadow-lg`}>
      {/* Header */}
      <div className="px-5 py-3.5 border-b border-slate-700 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <span className="text-lg">🤖</span>
          <h3 className="font-semibold text-slate-100 text-sm">AI Analysis</h3>
          {analysis.aiPowered && (
            <span className="text-[10px] bg-violet-500/20 text-violet-400 border border-violet-500/30 px-2 py-0.5 rounded-full font-medium">
              Gemini
            </span>
          )}
        </div>
        <span className="text-[10px] text-slate-500">
          {new Date(analysis.analyzedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
        </span>
      </div>

      <div className="p-5 space-y-4">
        {/* Metrics Row */}
        <div className="grid grid-cols-3 gap-3">
          <div className="bg-slate-900/60 rounded-lg p-3">
            <p className="text-[10px] text-slate-500 uppercase tracking-wider mb-1">Severity</p>
            <span className={`text-xs px-2 py-1 rounded border font-semibold ${config.badge}`}>
              {analysis.severity}
            </span>
          </div>
          <div className="bg-slate-900/60 rounded-lg p-3">
            <p className="text-[10px] text-slate-500 uppercase tracking-wider mb-1">Urgency</p>
            <p className="text-lg font-bold text-slate-100">{analysis.estimatedUrgency}<span className="text-slate-500 text-xs">/10</span></p>
          </div>
          <div className="bg-slate-900/60 rounded-lg p-3">
            <p className="text-[10px] text-slate-500 uppercase tracking-wider mb-1">Confidence</p>
            <div className="flex items-center gap-2">
              <p className="text-lg font-bold text-slate-100">{analysis.confidence}<span className="text-slate-500 text-xs">%</span></p>
            </div>
          </div>
        </div>

        {/* Confidence Bar */}
        <div className="w-full bg-slate-700 rounded-full h-1.5">
          <div
            className={`h-1.5 rounded-full transition-all ${config.bar}`}
            style={{ width: `${analysis.confidence}%` }}
          ></div>
        </div>

        {/* Summary */}
        <div>
          <p className="text-[10px] text-slate-500 uppercase tracking-wider mb-1.5">Summary</p>
          <p className="text-sm text-slate-300 leading-relaxed">{analysis.summary}</p>
        </div>

        {/* Recommended Response */}
        {analysis.recommendedResponse && (
          <div className="bg-cyan-500/10 border border-cyan-500/20 rounded-lg p-3">
            <p className="text-[10px] text-cyan-400 uppercase tracking-wider mb-1">Recommended Response</p>
            <p className="text-sm text-cyan-300 font-medium">{analysis.recommendedResponse}</p>
          </div>
        )}

        {/* Special Instructions */}
        {analysis.specialInstructions && (
          <div className="bg-amber-500/10 border border-amber-500/20 rounded-lg p-3">
            <p className="text-[10px] text-amber-400 uppercase tracking-wider mb-1">⚠ Special Instructions</p>
            <p className="text-sm text-amber-200">{analysis.specialInstructions}</p>
          </div>
        )}

        <p className="text-[10px] text-slate-600 leading-relaxed">
          {analysis.aiPowered
            ? 'Analysis generated by Google Gemini AI — verify before acting.'
            : 'Fallback analysis — AI service temporarily unavailable.'}
        </p>
      </div>
    </div>
  );
};

export default AIPanel;