import React from 'react';

const AIPanel = ({ analysis }) => {
  const severityConfig = {
    High: {
      color: 'border-red-500 bg-red-50',
      textColor: 'text-red-800',
      icon: '🔴'
    },
    Medium: {
      color: 'border-yellow-500 bg-yellow-50',
      textColor: 'text-yellow-800',
      icon: '🟡'
    },
    Low: {
      color: 'border-green-500 bg-green-50',
      textColor: 'text-green-800',
      icon: '🟢'
    }
  };

  const config = severityConfig[analysis.severity];

  return (
    <div className="bg-gradient-to-br from-purple-50 to-blue-50 rounded-2xl shadow-lg p-6 border-2 border-purple-200">
      <div className="flex items-center gap-3 mb-4">
        <span className="text-3xl">🤖</span>
        <div>
          <h3 className="text-lg font-bold text-gray-800">AI Analysis</h3>
          <p className="text-xs text-gray-500">
            Analyzed at {new Date(analysis.analyzedAt).toLocaleTimeString()}
          </p>
        </div>
      </div>

      <div className="space-y-4">
        {/* Severity */}
        <div className={`border-2 ${config.color} rounded-xl p-4`}>
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-600 font-semibold mb-1">Severity Level</p>
              <p className={`text-2xl font-bold ${config.textColor} flex items-center gap-2`}>
                <span>{config.icon}</span>
                {analysis.severity}
              </p>
            </div>
            <div className="text-right">
              <p className="text-sm text-gray-600 font-semibold mb-1">Confidence</p>
              <p className="text-2xl font-bold text-gray-800">{analysis.confidence}%</p>
            </div>
          </div>
        </div>

        {/* Summary */}
        <div className="bg-white rounded-xl p-4 border-2 border-gray-200">
          <p className="text-sm text-gray-600 font-semibold mb-2">AI Summary</p>
          <p className="text-gray-800 leading-relaxed">{analysis.summary}</p>
        </div>

        <div className="bg-blue-50 border border-blue-200 rounded-lg p-3 text-sm text-blue-800">
          ℹ️ This analysis is generated by AI and should be verified by the operator
        </div>
      </div>
    </div>
  );
};

export default AIPanel;