import React from 'react';

const AIPanel = ({ analysis }) => {
  const severityConfig = {
    High: {
      color: 'border-red-500 bg-red-50',
      textColor: 'text-red-800',
      icon: '🔴',
      bgGradient: 'from-red-50 to-pink-50'
    },
    Medium: {
      color: 'border-yellow-500 bg-yellow-50',
      textColor: 'text-yellow-800',
      icon: '🟡',
      bgGradient: 'from-yellow-50 to-orange-50'
    },
    Low: {
      color: 'border-green-500 bg-green-50',
      textColor: 'text-green-800',
      icon: '🟢',
      bgGradient: 'from-green-50 to-emerald-50'
    }
  };

  const config = severityConfig[analysis.severity];

  return (
    <div className={`bg-gradient-to-br ${config.bgGradient} rounded-2xl shadow-lg p-6 border-2 ${config.color}`}>
      <div className="flex items-center gap-3 mb-4">
        <span className="text-3xl">🤖</span>
        <div className="flex-1">
          <h3 className="text-lg font-bold text-gray-800 flex items-center gap-2">
            AI Analysis
            {analysis.aiPowered && (
              <span className="text-xs bg-purple-100 text-purple-700 px-2 py-1 rounded-full border border-purple-300">
                ✨ Gemini Powered
              </span>
            )}
          </h3>
          <p className="text-xs text-gray-500">
            Analyzed at {new Date(analysis.analyzedAt).toLocaleTimeString()}
          </p>
        </div>
      </div>

      <div className="space-y-4">
        {/* Severity */}
        <div className={`border-2 ${config.color} rounded-xl p-4`}>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <p className="text-sm text-gray-600 font-semibold mb-1">Severity Level</p>
              <p className={`text-2xl font-bold ${config.textColor} flex items-center gap-2`}>
                <span>{config.icon}</span>
                {analysis.severity}
              </p>
            </div>
            <div className="text-right">
              <p className="text-sm text-gray-600 font-semibold mb-1">Urgency Score</p>
              <p className="text-2xl font-bold text-gray-800">
                {analysis.estimatedUrgency}/10
              </p>
            </div>
          </div>
        </div>

        {/* Confidence */}
        <div className="bg-white rounded-xl p-4 border-2 border-gray-200">
          <div className="flex items-center justify-between mb-2">
            <p className="text-sm text-gray-600 font-semibold">AI Confidence</p>
            <p className="text-sm font-bold text-gray-800">{analysis.confidence}%</p>
          </div>
          <div className="w-full bg-gray-200 rounded-full h-3">
            <div 
              className={`h-3 rounded-full transition-all ${
                analysis.confidence >= 80 ? 'bg-green-500' :
                analysis.confidence >= 60 ? 'bg-yellow-500' :
                'bg-red-500'
              }`}
              style={{ width: `${analysis.confidence}%` }}
            ></div>
          </div>
        </div>

        {/* Summary */}
        <div className="bg-white rounded-xl p-4 border-2 border-gray-200">
          <p className="text-sm text-gray-600 font-semibold mb-2">AI Summary</p>
          <p className="text-gray-800 leading-relaxed">{analysis.summary}</p>
        </div>

        {/* Recommended Response */}
        {analysis.recommendedResponse && (
          <div className="bg-blue-50 rounded-xl p-4 border-2 border-blue-200">
            <p className="text-sm text-blue-600 font-semibold mb-2">Recommended Response</p>
            <p className="text-blue-800 font-medium">{analysis.recommendedResponse}</p>
          </div>
        )}

        {/* Special Instructions */}
        {analysis.specialInstructions && (
          <div className="bg-orange-50 rounded-xl p-4 border-2 border-orange-200">
            <p className="text-sm text-orange-600 font-semibold mb-2 flex items-center gap-2">
              <span>⚠️</span>
              Special Instructions
            </p>
            <p className="text-orange-800 text-sm">{analysis.specialInstructions}</p>
          </div>
        )}

        <div className="bg-purple-50 border border-purple-200 rounded-lg p-3 text-sm text-purple-800">
          ℹ️ {analysis.aiPowered 
            ? 'This analysis is generated by Google Gemini AI and should be verified by the operator' 
            : 'Fallback analysis used. AI service temporarily unavailable.'}
        </div>
      </div>
    </div>
  );
};

export default AIPanel;